### ISSUE TITLE
Bootscreen then nothing more

### ISSUE THREAD

**Issue by hme0354** [Ax-LED/volumio-pirate-audio#1]
I have installed your script on a raspberry pi zero w with an pirate audio dac hat. my OS is raspberry OS buster.
After the easy installation (thanks to you), I restarted the PI. But after the bootscreen "VOLUMIO booting ..." it freezes. What can I do?

**Comment by Ax-LED** [comment]
@hme0354 
i only tested with stable volumio version, which is based on OS Jessie. Which version of volumio do you use?
AxLED

**Comment by hme0354** [comment]
i don't know. how do i get the version?

**Comment by hme0354** [comment]
It was my mistake. I now use the volumio version OS and it works. thanks for your help.
