### ISSUE TITLE
Progress bar and Remaining time not updating

### ISSUE THREAD

**Issue by DrewBatchelor** [Ax-LED/volumio-pirate-audio#14]
Hi @Ax-LED,
Great plug in, thank you.
I see a small bug, that (on the Python 3 version on a Zero 2) the progress bar and remaing time display for a track do not update while a track is playing until a button is pressed.

**Comment by Ax-LED** [comment]
@DrewBatchelor 

to your questions:
- pixel or screen refresh depents on changes received via websockets. There is no periodical refresh so far.

AxLED
