### ISSUE TITLE
Static Display

### ISSUE THREAD

**Issue by mjbourgault** [Ax-LED/volumio-pirate-audio#16]
I have a Pirate Audio 3w amp speaker out HAT.  I followed your installation directions, (I couldnt find the plugin in the Volumio 3 settings) and I see a static looking image on the screen.  any ideas?  Also It appears that the A,B, X,Y buttons also do not work.  Sound Works.

**Comment by Ax-LED** [comment]
@mjbourgault 

the reason why you dont find my plugin on volumio 3 plugin store is, that i am waiting that my pull request get merged (is in the hand of volumio team).
Did you try installing as descriped here: [https://community.volumio.org/t/plugin-pirate-audio/44336/110](https://community.volumio.org/t/plugin-pirate-audio/44336/110)

This should work

AxLED
