### ISSUE TITLE
[Idea/Question]

### ISSUE THREAD

**Issue by sideshowbob84** [Ax-LED/volumio-pirate-audio#2]
Thank you very much for your plugin! It works lika a charm. I have the spotify Plugin installed on latest volumio and rasperry zero W. If i navigate on the pirates buttons, i can select Spotify and afterwards for example "My Albums".  But after selecting it, i get the message "Not Supported" / "nicht unterstützt" in German. I think this is normal since it is a plugin an not a "normal" music source. But maybe it is possible to add it. I have no idea how difficult it would be, so it is just an idea. 
Thanks a lot and kind regards

**Comment by Ax-LED** [comment]
@sideshowbob84 
good to hear you like the plugin. As i dont use spotify, it is hard to program my plugin the right way. 

- do you know if there is a free subscription to spotify, so i could register and try to get it working. 
- do you use spotify-plugin of volumio as well? 

Just to make sure i set up the right "development environment" on my volumio.

AxLED

**Comment by sideshowbob84** [comment]
@Ax-LED 
thanks a lot for your nice response. I use the spotify plugin of volumio, which is, if configured, a new music source (along with favorites, albums, etc. on the left side of volumio gui. There is a free subscription for spotify, but the plugin in volumio requiers a paid subscription. The first month is free. If needed i could make a new account and send you the credentials.

**Comment by Ax-LED** [comment]
@sideshowbob84 ,

i updated the code so it supports "spotify plugin" of volumio.
I am waiting that my Pull Request gets merged, details see [https://github.com/volumio/volumio-plugins/pull/552](https://github.com/volumio/volumio-plugins/pull/552)

AxLED
