### ISSUE TITLE
Plugin is great - however few minor issues could be solved

### ISSUE THREAD

**Issue by pjfoxpjfox** [Ax-LED/volumio-pirate-audio#3]
Thanks for the plugin. I have it working with PiZeroW and works very well. Previously I was using some python script to get what's played - to put on a screen, as well as printing buttons each time - next/prev/play etc. - now it works ultra super fine! Thanks!
I would like to ask if in configuration options would it be possible to add:
a) option to split title if longer than LCD (personally I removed drawing 'artist' as it in my case is radio name (and I know as it has logo in background). I did also moved 'title' to the top as more useful, especially that my radios are printing there name in format of "artist - title".

(less important) 
b) volume removal - I do use PirateAudio with Volumio as just net radio player - not using volume at all - would be nice to not have it on screen - and have just next/prev instead of vol up/down.

regards
pj

**Comment by Ax-LED** [comment]
@pjfoxpjfox ,

to your suggestions:
a) i am not planing to change this, it sounds to individual, but you can have a look at display.py to change it to your preferences
b) i updated the code of my plugin to v0.0.4 and wait that my pull request gets merged ([https://github.com/volumio/volumio-plugins/pull/552](https://github.com/volumio/volumio-plugins/pull/552)). In this version there is a prev/next feature in a sub menu, maybe this helps a little bit to get closer to the feature you where looking for.

AxLED
