### ISSUE TITLE
Button Problem

### ISSUE THREAD

**Issue by qbrickx** [Ax-LED/volumio-pirate-audio#4]
Hallo, the plugin works great, but i have a problem with the y-button. Out of the Box it doesn't work. So i set it from 20 to 24 in the volumio gui. The y button works now but the a button doesn't anymore.
I hope you can help me. 
It seems that you are german? Maybe you can awnser me in german too?

**Comment by Ax-LED** [comment]
see english text below
@qbrickx ,

welchen pirate audio hat hast du? Hat dein A Button schonmal funktioniert? Falls ja, einfach mal das Plugin über die volumio GUI neustarten und testen. Welche Plugins sind sonst noch installiert? Ist außer dem pirate audio hat noch was an den GPIO angeschlossen? Welchen Pi verwendest du?

Gruß

AxLED

----
english text
which pirate audio hat do you use? Has your A button worked before? If so, just restart the plugin via the volumio GUI and test it again. Are there other plugins installed? Is there anything else connected to the GPIO besides the pirate audio hat? Which pi are you using? 

Regards

AxLED

**Comment by qbrickx** [comment]
Hallo,

Danke für die schnelle Antwort.

Es funktioniert jetzt. Ich hatte die Zeilen mit dem fix vergessen in die config.txt zu schreiben.

**Comment by Ax-LED** [comment]
Hallo @qbrickx ,

du weißt schon, das das Plugin auch über die volumio GUI installierbar ist?

AxLED

---

Hi @qbrickx ,

you already know that the plugin can also be installed via the volumio GUI? 

AxLED
