### ISSUE TITLE
No Controls and Album/Song Information while Spotify-Connect playing

### ISSUE THREAD

**Issue by greewoo** [Ax-LED/volumio-pirate-audio#9]
No Controls (Play/Pause/Volume) and Album/Song Information while Spotify-Connect playing.

- while listening to Web Radio, controls and Song Information are shown
- while listening to Spotify-Connect, controls and Song Information are not shown

**Comment by Ax-LED** [comment]
@greewoo 
i only implemented the spotify plugin from author Volumio Team and not the plugin volumio spotifiy connect2.
So please try the "spotify" plugin instead

AxLED
